[package]
name = "ising-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
image = "0.24.6"
num-traits = "0.2.15"
rand = "0.8.5"
rfd = "0.11.4"
